apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DinBenDon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        dinbendon: web
    spec:
      containers:
      - name: dinbendon-web
        image: $$IMG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dinbendon-web
    role: service
  name: dinbendon-web
spec:
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  selector:
    dinbendon: web
