apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: bendon-db
    role: service
  name: bendon-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    bendon: db
